name: Product Service CD

on:
  workflow_run:
    workflows:
      - Product Service CI/CD
    types:
      - completed

jobs:
  deploy-product-service:

    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'master'

    runs-on: ubuntu-latest

    steps:

      - name: Deploy Product Service to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |

            # Login to Docker Hub
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | \
              docker login \
              -u "${{ secrets.DOCKERHUB_USERNAME }}" \
              --password-stdin

            # Pull Product Service image
            docker pull \
              ${{ secrets.DOCKERHUB_USERNAME }}/product-service:2.0

            # Stop existing container
            docker stop product-service || true

            # Remove existing container
            docker rm product-service || true

            # Start new container
            docker run -d \
              --name product-service \
              -p 5000:5001 \
              ${{ secrets.DOCKERHUB_USERNAME }}/product-service:2.0

            # Verify deployment
            docker ps